spring:
  profiles: production
  datasource:
    url: jdbc:h2:mem:reservationsDb
    driverClassName: org.h2.Driver
    username: sa
    password: ENC(6k0kI4IWKxWP/FUhhs4uSlzVs/5sVxqPVeradHw46aWuepAyCs8f4cw7EhiYjqN4)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 10
    idle-timeout: 10000
    max-lifetime: 30000


